### ISSUE TITLE
:confirm not firing

### ISSUE THREAD

**Issue by ryanflorence** [kevinvaldek/mootools-ujs#1]
I see you've got the window.rails.confirmed code in there but it doesn't ever ask to confirm with the regular scaffolding output, it simply submits the injected form without checking for the data-confirm attribute.

**Comment by kevinvaldek** [comment]
You're right. The driver incorrectly only caught data-confrim on remote requests. I've now fixed this so data-confirm always works. New tag is 0.2, also updated on the forge.

Thanks for the heads up!
