### ISSUE TITLE
MooTools 1.3 compatibility

### ISSUE THREAD

**Issue by evoL** [kevinvaldek/mootools-ujs#3]
The helper doesn't work yet with MooTools 1.3 (without compatibility).

**Comment by evoL** [comment]
Sorry, just needed to comment out the data- attribute code.

**Comment by kevinvaldek** [comment]
Thanks for the report. Yes that does help, but I think that the plugin should now be 1.3 ready straight away. I've made the changes: https://github.com/kevinvaldek/mootools-ujs/compare/b455f70f24...0275008b3d

There seems to be an issue with the Forge right now, so I can't update the plugin. But you can grab the latest version from the repo.
